### ISSUE TITLE
Cannot find module '@d3-stencil/interfaces'

### ISSUE THREAD

**Issue by ktamiola** [edgarordonez/d3-stencil#27]
I am trying to add a trivial PieChart to my PWA boilerplate and I keep getting `Cannot find module '@d3-stencil/interfaces'`. 

I have installed and saved `d3-stencil/interfaces'`. Is there an example / boilerplate I could use as a starting point?

**Comment by edgarordonez** [comment]
Hello @ktamiola 

I'd noticed some issues since I fired the last version. I'm working on it, and hopefully, at the very latest tomorrow evening (GMT+1), I'm gonna push a new stable release.

Sorry for the inconvenience. I'm thinking about to add the e2e tests asap to avoid that this could happen again.

🙏

**Comment by ktamiola** [comment]
@edgarordonez much appreciated, buddy! I do believe my team should be also able to contribute very soon.

**Comment by edgarordonez** [comment]
Hello @ktamiola,

I've solved these issues, so you should be able to start using d3-stencil again. 🎉 

I'll invest more time next weekend to address other things and improve the quality of the current codebase.

So any contribution would be excellent! :)

I'm gonna wait for close this issue, feel free to add a new one or write here something that you may find.

Thanks!
